#!/bin/bash

# https://api.etherscan.io/api
#    ?module=contract
#    &action=getsourcecode
#    &address=0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413
#    &apikey=YourApiKeyToken


# from stdin, we get a csv with no header. the fields are calltype,selector,from
# selector might have quotes around it, and might have commas in it
# we want to extract the from field and hit the etherscan api to get the contract name
# we then want to output calltype, selector, from, contract name

while IFS=, read -r calltype selector from; do
    response=$(curl -s "https://api.etherscan.io/api?module=contract&action=getsourcecode&address=$from&apikey=$ETHERSCAN_API_KEY")
    contract_name=$(echo $response | jq -r '.result[0].ContractName')
    implementation=$(echo $response | jq -r '.result[0].Implementation')
    if [ "$implementation" != "" ]; then
        implementation_name=$(curl -s "https://api.etherscan.io/api?module=contract&action=getsourcecode&address=$implementation&apikey=$ETHERSCAN_API_KEY" | jq -r '.result[0].ContractName')
        contract_name="$contract_name -> $implementation_name"
    fi
    echo "$calltype,$selector,$from,\"$contract_name\""
done