#!/bin/bash

while IFS=, read -r calltype selector from; do
    pretty=$(cast 4 "$selector" 2> /dev/null)
    if [ $? -ne 0 ]; then
        pretty=$selector
    fi
    echo "$calltype,\"$pretty\",$from"
done