[package]
name = "create-spreadsheet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89" }
serde_json = "1.0"
xlsxwriter = "0.6.0"
rust_xlsxwriter = { version = "0.79.0", features = ["constant_memory"] }
